# For general help on the options
# # http://jekyllrb.com/docs/configuration/

# Site wide configuration

title:            Luca Gerhards 
locale:           da_DK
#url:              https://commicgroup.ku.dk
#url:              http://127.0.0.1:4000/

# RSS Feed configuration
name: Luca Gerhards
description: Webpage of Luca Gerhards
rss: true

# Jekyll configuration
permalink:   /:categories/:title/
post_dir: false
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-paginate

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

# Github Specific Settings that *cannot* be changed
# To ensure proper reproducibility
# https://help.github.com/articles/configuring-jekyll/
gist:
  noscript: false
github: [metadata]
highlighter: rouge
incremental: false
lsi: false
safe: true

# Site owner
owner:
  name: Luca Gerhards
  avatar: sections.png
  bio: "Spin Dnyamics and Quantum Chemistry."
  github: das0mann

include: [".htaccess"]
#exclude: [vendor, ruby]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "_utilities"]
